In [7]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
data = pd.read_csv('Advertising.csv', usecols = ['TV','radio','newspaper','sales'])
X = data.iloc[:,:-1]
y = data.sales

In [2]:
X = sm.add_constant(X)

In [3]:
X[:5]

const     TV  radio  newspaper
0    1.0  230.1   37.8       69.2
1    1.0   44.5   39.3       45.1
2    1.0   17.2   45.9       69.3
3    1.0  151.5   41.3       58.5
4    1.0  180.8   10.8       58.4

In [4]:
model = sm.OLS(y,X)

In [5]:
result = model.fit()
result.params

const        2.938889
TV           0.045765
radio        0.188530
newspaper   -0.001037
dtype: float64

In [6]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Sun, 18 Oct 2020   Prob (F-statistic):           1.58e-96
Time:                        23:54:52   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
radio          0.1885      0.009     21.893      0.000       0.172       0.206
newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [10]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [36]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)
model.coef_
print('The Paramter values using ScikitLearn Linear regression')
count = 1
for i in model.coef_:
    print('a{} : {}'.format(count,i))
    count+=1

The Paramter values using ScikitLearn Linear regression
a1 : 0.0457646454553976
a2 : 0.18853001691820442
a3 : -0.0010374930424763285


In [37]:
from scipy.linalg import lstsq
theta_best = lstsq(X,y,cond = 1e-6)
print('The Paramter values using Scipy Least Square')
count = 1
for i in theta_best[0]:
    print('a{} : {}'.format(count,i))
    count+=1

The Paramter values using Scipy Least Square
a1 : 0.05379187695222015
a2 : 0.22222731066570012
a3 : 0.016816388144535593


In [38]:
import numpy as np
theta_best_np = np.linalg.lstsq(X,y,rcond = 1e-6)
count = 1
for i in theta_best_np[0]:
    print('a{} : {}'.format(count,i))
    count+=1

a1 : 0.05379187695222015
a2 : 0.22222731066570012
a3 : 0.016816388144535593


In [41]:
theta_pseudo = np.linalg.pinv(X).dot(y)
count = 1
for i in theta_pseudo:
    print('a{} : {}'.format(count,i))
    count+=1

a1 : 0.05379187695222017
a2 : 0.22222731066570028
a3 : 0.01681638814453562


In [44]:
np.linalg.svd(X)

(array([[-9.81922513e-02,  7.92030586e-02, -3.63636995e-02, ...,
         -6.98394835e-02, -1.20880519e-01, -9.20389795e-02],
        [-2.26350697e-02,  1.21499859e-01,  5.77325535e-02, ...,
          4.22662455e-02, -2.30593089e-02,  7.05215552e-02],
        [-1.36463007e-02,  1.95116739e-01,  3.11170434e-02, ...,
          4.99304119e-02, -4.36403741e-02,  5.68405599e-02],
        ...,
        [-7.15021402e-02, -6.34609241e-02, -1.82097441e-04, ...,
          9.91679705e-01, -5.61927539e-03, -1.11584391e-02],
        [-1.19550808e-01,  5.10123507e-02, -1.78801119e-02, ...,
         -4.93051019e-03,  9.85080578e-01, -6.56255527e-03],
        [-9.36037804e-02, -8.67938947e-02, -1.71653934e-02, ...,
         -1.10060078e-02, -7.50515335e-03,  9.84950510e-01]]),
 array([2455.13412965,  398.51120354,  194.49477131]),
 array([[-0.97964709, -0.12088787, -0.16024264],
        [-0.19867788,  0.47017136,  0.85992208],
        [-0.02861265,  0.87425683, -0.48461975]]))